
/*地图数据*/
var floot1=[
	[DOOR2, SPACE, OKEY , M43  , M20  , M43  , SPACE, SPACE, SPACE, SPACE, SPACE],
	[BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, SPACE],
	[BOTT2, SPACE, M78  , ODOOR, SPACE, BLOCK, BOTT2, OKEY , BOTT2, BLOCK, SPACE],
	[OKEY , M78  , RDIAM, BLOCK, SPACE, BLOCK, BOTT2, OKEY , BOTT2, BLOCK, SPACE],
	[BLOCK, ODOOR, BLOCK, BLOCK, SPACE, BLOCK, BLOCK, BLOCK, M49  , BLOCK, SPACE],
	[OKEY , M32  , SPACE, BLOCK, SPACE, ODOOR, M47  , M43  , M1   , BLOCK, SPACE],
	[SPACE, SPACE, BKEY , BLOCK, SPACE, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, SPACE],
	[BLOCK, ODOOR, BLOCK, BLOCK, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE],
	[SPACE, M32  , SPACE, BLOCK, BLOCK, RDOOR, BLOCK, BLOCK, BLOCK, ODOOR, BLOCK],
	[BOTT2, BOTT2, OKEY , BLOCK, RKEY,  SPACE, XZ   , BLOCK, OKEY , M2   , BKEY],
	[BOTT2, GWXX , OKEY , BLOCK, BLOCK, DOOR1, BLOCK, BLOCK, OKEY , OKEY , OKEY]
]

var floot2=[
	[BLOCK, BLOCK, SPACE, M34  , SPACE, BLOCK, RDIAM, BDIAM, OKEY , RKEY , BLOCK],
	[DOOR1, BLOCK, BDIAM, BLOCK, BOTT1, BLOCK, RDIAM, BDIAM, OKEY , BKEY , BLOCK],
	[SPACE, BLOCK, OKEY , BLOCK, OKEY , BLOCK, RDIAM, BDIAM, OKEY , M88  , BLOCK],
	[SPACE, BLOCK, OKEY , BLOCK, OKEY , BLOCK, BLOCK, BLOCK, BLOCK, ODOOR , BLOCK],
	[SPACE, BLOCK, SPACE, BLOCK, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, BLOCK],
	[SPACE, BLOCK, ODOOR, BLOCK, BLOCK, ODOOR, BLOCK, BLOCK, ODOOR, BLOCK, BLOCK],
	[SPACE, SDOOR, SPACE, SPACE, SPACE, SPACE, BLOCK, SPACE, M88  , SPACE, BLOCK],
	[SPACE, BLOCK, ODOOR, BLOCK, BLOCK, BDOOR, BLOCK, SPACE, BLOCK, SPACE, BLOCK],
	[SPACE, BLOCK, OKEY , BLOCK, BOTT1, BOTT2, BLOCK, SPACE, BLOCK, SPACE, BLOCK],
	[DOOR2, BLOCK, OKEY , BLOCK, BOTT1, BOTT2, BLOCK, SPACE, BLOCK, SPACE, BLOCK],
	[BLOCK, BLOCK, RDIAM, BLOCK, BOTT1, BOTT2, BLOCK, SPACE, BLOCK, SPACE, BLOCK]
]

var floot3=[
	[JIAN , M20  , OKEY , BLOCK, SHOP3, -1000, -1000, BLOCK, BLOCK, BLOCK, BLOCK],
	[M20  , OKEY , SPACE, BLOCK, SPACE, SPACE, SPACE, BLOCK, SPACE, M1   , SPACE],
	[OKEY , M78  , SPACE, BLOCK, BLOCK, ODOOR, BLOCK, BLOCK, SPACE, BLOCK, SPACE],
	[BLOCK, ODOOR, BLOCK, BLOCK, SPACE, M78  , SPACE, BLOCK, OKEY , BLOCK, M20  ],
	[SPACE, SPACE, SPACE, BLOCK, BLOCK, BLOCK, SPACE, BLOCK, OKEY , BLOCK, M1   ],
	[M43  , BLOCK, SPACE, M1   , M20  , M1   , SPACE, BLOCK, OKEY , BLOCK, M20  ],
	[M43  , BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, SPACE, SPACE, SPACE, BLOCK, SPACE],
	[SPACE, SPACE, SPACE, SPACE, SPACE, BLOCK, BLOCK, ODOOR, BLOCK, BLOCK, SPACE],
	[BLOCK, BLOCK, BLOCK, BLOCK, M1   , BLOCK, M20  , SPACE, M20  , BLOCK, SPACE],
	[BLOCK, SPACE, SPACE, SPACE, SPACE, BLOCK, BDIAM, M1   , OKEY , BLOCK, SPACE],
	[DOOR1, SPACE, BLOCK, BLOCK, BLOCK, BLOCK, RDIAM, BOTT1, OKEY , BLOCK, DOOR2]
] 
var floot4=[
	[SPACE, M49  , SPACE, BLOCK, SPACE, THIEF, SPACE, BLOCK, SPACE, M49  , SPACE],
	[ODOOR, BLOCK, ODOOR, BLOCK, SPACE, SPACE, SPACE, BLOCK, ODOOR, BLOCK, ODOOR],
	[SPACE, BLOCK, SPACE, BLOCK, BLOCK, ODOOR, BLOCK, BLOCK, SPACE, BLOCK, SPACE],
	[SPACE, BLOCK, M78  , BLOCK, M55  , M11  , M55  , BLOCK, M78  , BLOCK, SPACE],
	[M1   , BLOCK, BOTT1, BLOCK, BDIAM, M55  , BDIAM, BLOCK, BOTT1, BLOCK, M1   ],
	[M1   , BLOCK, BOTT1, BLOCK, BLOCK, RDOOR, BLOCK, BLOCK, BOTT1, BLOCK, M1   ],
	[M20  , BLOCK, SPACE, BLOCK, M2   , M41  , M2   , BLOCK, SPACE, BLOCK, M20  ],
	[SPACE, BLOCK, SPACE, BLOCK, RDIAM, M2   , RDIAM, BLOCK, SPACE, BLOCK, SPACE],
	[SPACE, BLOCK, SPACE, BLOCK, BLOCK, BDOOR, BLOCK, BLOCK, SPACE, BLOCK, SPACE],
	[SPACE, BLOCK, SPACE, BLOCK, OKEY , SPACE, OKEY , BLOCK, SPACE, BLOCK, SPACE],
	[DOOR2, BLOCK, SPACE, M49  , SPACE, SPACE, SPACE, M49  , SPACE, BLOCK, DOOR1]
]
var floot5=[
	[OKEY , BLOCK, BOTT1, BLOCK, BOTT1, M47  , SPACE, SPACE, M47 , OKEY , BKEY ],
	[SPACE, BLOCK, RDIAM, BLOCK, M47  , SPACE, SPACE, SPACE, SPACE, M47 , OKEY ],
	[M55  , BLOCK, SPACE, BLOCK, M32  , SPACE, BLOCK, BLOCK, ODOOR, BLOCK, BLOCK],
	[SPACE, ODOOR, M47  , BLOCK, DUN  , M32  , BLOCK, SPACE, M2   , M32  , KEY5 ],
	[M55  , BLOCK, SPACE, BLOCK, BLOCK, BLOCK, BLOCK, SPACE, SPACE, SPACE, M32  ],
	[RDIAM, BLOCK, SPACE, SPACE, SPACE, M1   , M78  , SPACE, SPACE, SPACE, SPACE],
	[BDIAM, BLOCK, BLOCK, M49  , BLOCK, BLOCK, BLOCK, BLOCK, SPACE, SPACE, SPACE],
	[SPACE, EXP5 , BLOCK, M49  , BLOCK, SPACE, SPACE, SPACE, M2   , M41  , SPACE],
	[BLOCK, BLOCK, BLOCK, M1   , BLOCK, ODOOR, BLOCK, BDOOR, BLOCK, ODOOR, BLOCK],
	[SPACE, SPACE, BLOCK, SPACE, BLOCK, M1   , BLOCK, BDIAM, ODOOR, SPACE, BLOCK],
	[DOOR1, SPACE, M1   , SPACE, SPACE, SPACE, BLOCK, OKEY , BLOCK, DOOR2, BLOCK]
] 
var floot6=[
	[XFY  , M56  , BLOCK, BDIAM, BLOCK, OKEY , M45  , SPACE, BLOCK, BOTT2, BOTT2],
	[M56  , OKEY , BLOCK, RDIAM, BLOCK, SPACE, OKEY , M45  , BLOCK, M77  , BOTT2],
	[OKEY , M11  , BDOOR, SPACE, BDOOR, M11  , SPACE, OKEY , BLOCK, SPACE, M77  ],
	[SPACE, SPACE, BLOCK, M41  , BLOCK, SPACE, SPACE, SPACE, BLOCK, M15  , SPACE],
	[BLOCK, BLOCK, BLOCK, RDOOR, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, ODOOR, BLOCK],
	[SPACE, SPACE, M94  , SPACE, OKEY , OKEY , OKEY , SPACE, M94  , SPACE, SPACE],
	[SPACE, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK],
	[SPACE, BLOCK, M55  , ODOOR, M55  , SPACE, SPACE, SPACE, SPACE, SPACE, BLOCK],
	[SPACE, BLOCK, ODOOR, BLOCK, ODOOR, BLOCK, BLOCK, BLOCK, BLOCK, BDOOR, BLOCK],
	[SPACE, BLOCK, M55  , BLOCK, SPACE, SPACE, BLOCK, BLOCK, SPACE, SPACE, BLOCK],
	[SPACE, SPACE, SPACE, BLOCK, DOOR2, SPACE, ODOOR, ODOOR, SPACE, DOOR1, BLOCK]
] 

var floot7=[
	[DOOR2, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, BLOCK, BLOCK, BLOCK],
	[BLOCK, BLOCK, SPACE, M11  , BLOCK, SPACE, BLOCK, M56  , SPACE, BLOCK, BLOCK],
	[BLOCK, SPACE, M11  , BDIAM, BLOCK, M21  , BLOCK, RDIAM, M56  , SPACE, BLOCK],
	[SPACE, SPACE, BLOCK, BLOCK, BLOCK, SPACE, BLOCK, BLOCK, BLOCK, SPACE, SPACE],
	[SPACE, SPACE, BDOOR, M21  , SPACE, SZJ  , SPACE, M21  , BDOOR, SPACE, SPACE],
	[SPACE, BLOCK, BLOCK, BLOCK, BLOCK, SPACE, BLOCK, BLOCK, BLOCK, BLOCK, SPACE],
	[SPACE, BLOCK, BOTT1, RDIAM, BLOCK, M21  , BLOCK, BDIAM, BOTT1, BLOCK, SPACE],
	[SPACE, BLOCK, OKEY , BOTT1, BLOCK, BDOOR, BLOCK, BOTT1, OKEY , BLOCK, SPACE],
	[SPACE, BLOCK, BLOCK, BKEY , BKEY , BOTT2, BKEY , BKEY , BLOCK, BLOCK, SPACE],
	[SPACE, SPACE, BLOCK, BLOCK, BLOCK, RDOOR, BLOCK, BLOCK, BLOCK, SPACE, SPACE],
	[BLOCK, SPACE, SPACE, ODOOR, DOOR1, SPACE, SPACE, ODOOR, SPACE, SPACE, BLOCK]
] 
var floot8=[
	[DOOR1, BLOCK, SPACE, SPACE, SPACE, SPACE, BLOCK, SPACE, OKEY , M56  , SPACE],
	[SPACE, BLOCK, SPACE, BLOCK, BLOCK, ODOOR, BLOCK, ODOOR, BLOCK, BLOCK, SPACE],
	[SPACE, BLOCK, SPACE, BLOCK, SPACE, SPACE, BDOOR, SPACE, SPACE, BLOCK, RDIAM],
	[SPACE, BLOCK, SPACE, BLOCK, M10  , BLOCK, BLOCK, BLOCK, M55  , BLOCK, M49  ],
	[M55  , BLOCK, SPACE, BLOCK, BOTT2, BLOCK, DOOR2, SPACE, SPACE, BLOCK, M49  ],
	[M11  , BLOCK, BDIAM, BLOCK, BOTT2, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, SPACE],
	[M55  , BLOCK, M49  , BLOCK, SPACE, SPACE, SPACE, BLOCK, SPACE, M11  , SPACE],
	[SPACE, BLOCK, M49  , BLOCK, BLOCK, BLOCK, M41  , BLOCK, ODOOR, BLOCK, BLOCK],
	[SPACE, BLOCK, SPACE, M56  , SPACE, BLOCK, M56  , BLOCK, SPACE, SPACE, SPACE],
	[SPACE, BLOCK, BLOCK, BLOCK, ODOOR, BLOCK, SPACE, BLOCK, BLOCK, BLOCK, SPACE],
	[SPACE, SPACE, SPACE, SPACE, SPACE, BLOCK, SPACE, M44  , M21  , M44  , SPACE]
] 
var floot9=[
	[FP   , OKEY , SPACE, BLOCK, BLOCK, BLOCK, SPACE, SPACE, SPACE, BLOCK, SPACE],
	[OKEY , SPACE, M15  , ODOOR, SPACE, SPACE, SPACE, BLOCK, SPACE, ODOOR, M56  ],
	[BLOCK, ODOOR, BLOCK, BLOCK, SPACE, BLOCK, BLOCK, BLOCK, SPACE, BLOCK, OKEY ],
	[SPACE, SPACE, SPACE, BLOCK, SPACE, BLOCK, SPACE, SPACE, SPACE, BLOCK, OKEY ],
	[SPACE, SPACE, SPACE, RDOOR, SPACE, BLOCK, DOOR1, BLOCK, SPACE, BLOCK, BOTT1],
	[BLOCK, BDOOR, BLOCK, BLOCK, SPACE, BLOCK, BLOCK, BLOCK, SPACE, BLOCK, BLOCK],
	[BDIAM, M79  , RDIAM, BLOCK, M10  , BLOCK, DOOR2, BLOCK, SPACE, BLOCK, BOTT1],
	[BLOCK, ODOOR, BLOCK, BLOCK, SPACE, SPACE, SPACE, ODOOR, SPACE, BLOCK, OKEY ],
	[M56  , BOTT1, M56  , BLOCK, BLOCK, BDOOR, BLOCK, BLOCK, SPACE, BLOCK, OKEY ],
	[BKEY , M56  , BOTT1, BLOCK, M77  , M10  , M77  , BLOCK, SPACE, ODOOR, M56  ],
	[JIAN9, BKEY , M56  , ODOOR, BOTT2, M77  , BOTT2, BLOCK, SPACE, BLOCK, SPACE]
] 
var floot10=[
	[SPACE, BLOCK, BLOCK, BDIAM, M15  , BLOCK, M15  , RDIAM, BLOCK, BLOCK, SPACE],
	[SPACE, SPACE, BLOCK, BLOCK, ODOOR, BLOCK, ODOOR, BLOCK, BLOCK, SPACE, M79  ],
	[SPACE, SPACE, SPACE, SPACE, SPACE, BLOCK, SPACE, SPACE, SPACE, M79  , BOTT2],
	[SPACE, BLOCK, SPACE, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, SPACE, BLOCK, BLOCK],
	[M55  , BLOCK, SPACE, SPACE, OKEY , OKEY , OKEY , SPACE, SPACE, BLOCK, OKEY ],
	[M11  , BLOCK, SPACE, BLOCK, BLOCK, BLOCK, BLOCK, ODOOR, BLOCK, BLOCK, OKEY ],
	[M55  , BLOCK, SPACE, SPACE, SPACE, DOOR1, BLOCK, SPACE, ODOOR, M11  , SPACE],
	[SPACE, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, ODOOR, BLOCK, BLOCK, SPACE],
	[SPACE, BLOCK, BOTT1, BDIAM, RDIAM, BLOCK, SPACE, M11  , SPACE, BLOCK, OKEY ],
	[SPACE, BLOCK, BOTT1, BDIAM, RDIAM, RDOOR, M10  , BLOCK, M10  , BLOCK, OKEY ],
	[DOOR2, BLOCK, BOTT1, BDIAM, RDIAM, BLOCK, BKEY , BLOCK, BKEY , BLOCK, BOTT1]
] 
var floot11=[
	[BOTT1, BLOCK, OKEY , BLOCK, BKEY , BLOCK, RKEY , BLOCK, BOTT2, SPACE, BOTT2],
	[BOTT1, BLOCK, OKEY , BLOCK, BKEY , BLOCK, RKEY , BLOCK, M73  , M76  , M73  ],
	[BOTT1, BLOCK, OKEY , BLOCK, BKEY , BLOCK, RKEY , BLOCK, SPACE, M73  , SPACE],
	[ODOOR, BLOCK, ODOOR, BLOCK, ODOOR, BLOCK, ODOOR, BLOCK, BLOCK, BDOOR, BLOCK],
	[SPACE, SPACE, SPACE, SPACE, SPACE, BLOCK, SPACE, SPACE, SPACE, SPACE, SPACE],
	[ODOOR, BLOCK, BLOCK, BDOOR, BLOCK, BLOCK, BLOCK, BDOOR, BLOCK, BLOCK, ODOOR],
	[BDIAM, BLOCK, SPACE, M73  , BOTT2, M29  , BOTT2, M73  , SPACE, BLOCK, RDIAM],
	[BDIAM, BLOCK, M15  , BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, M15  , BLOCK, RDIAM],
	[BDIAM, BLOCK, M15  , BLOCK, SHO11, -2000, -2000, BLOCK, M15  , BLOCK, RDIAM],
	[BLOCK, BLOCK, RDOOR, BLOCK, BOTT1, SPACE, BOTT1, BLOCK, RDOOR, BLOCK, BLOCK],
	[DOOR1, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, DOOR2]
] 
var floot12=[
	[SKE12, BDIAM, BLOCK, SPACE, M88  , M34  , M88  , SPACE, BLOCK, BOTT2, AX   ],
	[RDIAM, SPACE, BLOCK, SPACE, BLOCK, ODOOR, BLOCK, SPACE, BLOCK, SPACE, BOTT2],
	[SPACE, SPACE, BLOCK, SPACE, BLOCK, M34  , BLOCK, SPACE, BLOCK, SPACE, SPACE],
	[SPACE, M29  , BLOCK, SPACE, BLOCK, OKEY , BLOCK, SPACE, BLOCK, M46  , SPACE],
	[M29  , M68  , BLOCK, SPACE, BLOCK, OKEY , BLOCK, SPACE, BLOCK, M50  , M46  ],
	[BLOCK, BDOOR, BLOCK, SPACE, BLOCK, BOTT1, BLOCK, SPACE, BLOCK, BKEY , BLOCK],
	[SPACE, SPACE, SPACE, SPACE, BLOCK, BOTT1, BLOCK, SPACE, SPACE, SPACE, SPACE],
	[BLOCK, BLOCK, BLOCK, SPACE, BLOCK, BLOCK, BLOCK, SPACE, BLOCK, BLOCK, BLOCK],
	[BDIAM, M29  , ODOOR, M73  , M73  , M76  , M73  , M73  , ODOOR, M29  , RDIAM],
	[BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BDOOR, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK],
	[DOOR2, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, DOOR1]
] 
var floot13=[
	[SPACE, M29  , SPACE, SPACE, SPACE, SPACE, SPACE, BLOCK, SPACE, M68 , SPACE],
	[SPACE, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, ODOOR, BLOCK, SPACE, BLOCK, SPACE],
	[SPACE, BLOCK, SPACE, SPACE, M73  , SPACE, SPACE, BLOCK, SPACE, BLOCK, SPACE],
	[BOTT2, BLOCK, RDOOR, BLOCK, BLOCK, BLOCK, SPACE, BLOCK, SPACE, BLOCK, SPACE],
	[M88  , BLOCK, SPACE, SPACE, M68  , BLOCK, M73  , BLOCK, RDIAM, BLOCK, SPACE],
	[M34  , BLOCK, SPACE, M31  , SPACE, BLOCK, M76  , BLOCK, RDIAM, BLOCK, SPACE],
	[M88  , BLOCK, M68  , SPACE, EXP13, BLOCK, M73  , BLOCK, RDIAM, BLOCK, BDIAM],
	[SPACE, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, SPACE, BLOCK, SPACE, BLOCK, BDIAM],
	[SPACE, M88  , SPACE, BLOCK, SPACE, SPACE, SPACE, M68  , SPACE, BLOCK, BDIAM],
	[BLOCK, BLOCK, SPACE, BLOCK, BOTT2, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, SPACE],
	[DOOR1, SPACE, SPACE, BDOOR, SPACE, DOOR2, BLOCK, XFY  , M31  , ODOOR, SPACE]
] 
var floot14=[
	[BLOCK, SPACE, M46  , OKEY , DOOR2, SPACE, SPACE, SPACE, SPACE, SPACE, BLOCK],
	[BLOCK, SPACE, BOTT2, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BOTT2, SPACE, BLOCK],
	[BLOCK, SPACE, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, SPACE, BLOCK],
	[BLOCK, SPACE, BLOCK, BLOCK, BLOCK, SS   , BLOCK, BLOCK, BLOCK, SPACE, BLOCK],
	[BLOCK, SPACE, BLOCK, BLOCK, BLOCK, SPACE, BLOCK, BLOCK, BLOCK, SPACE, BLOCK],
	[BLOCK, SPACE, BOTT1, BLOCK, BLOCK, M68  , BLOCK, BLOCK, BOTT1, SPACE, BLOCK],
	[BLOCK, SPACE, SPACE, SPACE, BLOCK, M31  , BLOCK, SPACE, SPACE, SPACE, BLOCK],
	[BLOCK, SPACE, SPACE, SPACE, BLOCK, M68  , BLOCK, SPACE, SPACE, SPACE, BLOCK],
	[BLOCK, SPACE, SPACE, SPACE, BLOCK, BDOOR, BLOCK, SPACE, SPACE, SPACE, BLOCK],
	[BLOCK, M73  , M76  , M73  , BDOOR, SPACE, BDOOR, M73  , M76  , M73  , BLOCK],
	[BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, DOOR1, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK]
] 
var floot15=[
	[SPACE, SPACE, SPACE, SPACE, DOOR1, BLOK2, DOOR2, SPACE, SPACE, SPACE, SPACE],
	[SPACE, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, SPACE],
	[SPACE, BLOK2, BLOK2, BLOCK, BLOCK, BLOCK, BLOCK, BLOCK, BLOK2, BLOK2, SPACE],
	[SPACE, BLOK2, BLOCK, BLOCK, LR15 , BLOCK, SR15 , BLOCK, BLOCK, BLOK2, SPACE],
	[SPACE, BLOK2, BLOCK, BLOCK, BDIAM, BLOCK, BDIAM, BLOCK, BLOCK, BLOK2, SPACE],
	[SPACE, BLOK2, BLOCK, BLOCK, RDIAM, BLOCK, RDIAM, BLOCK, BLOCK, BLOK2, SPACE],
	[SPACE, BLOK2, BLOK2, BLOCK, SPACE, BLOCK, SPACE, BLOCK, BLOK2, BLOK2, SPACE],
	[SPACE, BLOK2, BLOK2, BLOCK, ODOOR, BLOCK, ODOOR, BLOCK, BLOK2, BLOK2, SPACE],
	[SPACE, BLOK2, BLOK2, BLOK2, SPACE, SPACE, SPACE, BLOK2, BLOK2, BLOK2, SPACE],
	[SPACE, BLOK2, BLOK2, BLOK2, BLOK2, RDOOR, BLOK2, BLOK2, BLOK2, BLOK2, SPACE],
	[SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE]
] 
var floot16=[
	[BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, SPACE, DOOR1, BLOK2, BLOK2, BLOK2, BLOK2],
	[BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, SPACE, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2],
	[BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, SPACE, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2],
	[BLOK2, BLOK2, BLOK2, BLOK2, BLOCK, RDOOR, BLOCK, BLOK2, BLOK2, BLOK2, BLOK2],
	[BLOK2, BLOK2, BLOK2, BLOCK, SPACE, SPACE, BLOCK, BLOCK, BLOK2, BLOK2, BLOK2],
	[BLOK2, BLOK2, BLOK2, BLOCK, BLOCK, M65  , BLOCK, BLOCK, BLOK2, BLOK2, BLOK2],
	[BLOK2, BLOK2, BLOK2, BLOCK, BLOCK, SPACE, BLOCK, BLOCK, BLOK2, BLOK2, BLOK2],
	[BLOK2, BLOK2, BLOK2, BLOCK, BLOCK, DOOR2, BLOCK, BLOCK, BLOK2, BLOK2, BLOK2],
	[BLOK2, BLOK2, BLOK2, BLOK2, BLOCK, BLOCK, BLOCK, BLOK2, BLOK2, BLOK2, BLOK2],
	[BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2],
	[BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2]
] 
var floot17=[
	[BLOK2, M46  , M31  , SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, M46  ],
	[BLOK2, M31  , BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, SPACE],
	[BLOK2, SPACE, BLOK2, M46  , SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, M46  ],
	[BLOK2, SPACE, BLOK2, SPACE, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2],
	[BLOK2, SPACE, BLOK2, SPACE, BLOK2, M46  , SPACE, SPACE, SPACE, M46  , BLOK2],
	[BLOK2, SPACE, BLOK2, M46  , SPACE, SPACE, BLOK2, BLOK2, BLOK2, SPACE, BLOK2],
	[BLOK2, SPACE, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, M46  , SPACE, M46  , BLOK2],
	[BLOK2, M31  , BLOK2, BLOK2, BLOK2, DOOR1, BLOK2, SPACE, BLOK2, BLOK2, BLOK2],
	[BLOK2, M46  , M31  , SPACE, M91  , SPACE, BLOK2, M46  , SPACE, SPACE, M46  ],
	[BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, SPACE],
	[DOOR2, SPACE, M91  , SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, M46  ]
] 
var floot18=[
	[BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2],
	[BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2],
	[BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2],
	[BLOK2, BLOK2, BLOK2, BLOK2, BLOCK, BLOK2, BLOCK, BLOK2, BLOK2, BLOK2, BLOK2],
	[BLOK2, BLOK2, BLOK2, BLOCK, BLOCK, BLOK2, BLOCK, BLOCK, BLOK2, BLOK2, BLOK2],
	[BLOK2, BLOK2, BLOK2, BLOCK, BLOCK, BLOK2, BLOCK, BLOCK, BLOK2, BLOK2, BLOK2],
	[BLOK2, BLOK2, BLOK2, BLOCK, BLOCK, BLOK2, BLOCK, BLOCK, BLOK2, BLOK2, BLOK2],
	[BLOK2, BLOK2, BLOK2, BLOK2, BLOCK, BLOK2, BLOCK, BLOK2, BLOK2, BLOK2, BLOK2],
	[BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2],
	[BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2],
	[DOOR1, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, DOOR2]
] 
var floot19=[
	[SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE],
	[SPACE, BLOK2, SPACE, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, SPACE, BLOK2, SPACE],
	[SPACE, BLOK2, SPACE, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, SPACE, BLOK2, SPACE],
	[SPACE, BLOK2, SPACE, BLOK2, BLOK2, DOOR2, BLOK2, BLOK2, SPACE, BLOK2, SPACE],
	[SPACE, BLOK2, SPACE, BLOK2, BLOK2, SPACE, BLOK2, BLOK2, SPACE, BLOK2, SPACE],
	[SPACE, BLOK2, M65  , BLOK2, BLOK2, SPACE, BLOK2, BLOK2, M65  , BLOK2, SPACE],
	[SPACE, BLOK2, SPACE, BLOK2, BLOK2, M67  , BLOK2, BLOK2, SPACE, BLOK2, SPACE],
	[SPACE, BLOK2, JIAN19, BLOK2, BLOK2, SPACE, BLOK2, BLOK2, SPACE, BLOK2, SPACE],
	[SPACE, BLOK2, BLOK2, BLOK2, BLOK2, SPACE, BLOK2, BLOK2, BLOK2, BLOK2, SPACE],
	[SPACE, BLOK2, BLOK2, BLOK2, BLOK2, SPACE, BLOK2, BLOK2, BLOK2, BLOK2, SPACE],
	[SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, DOOR1]
] 
var floot20=[
	[M91  , RDIAM, M21  , BOTT1, M31  , RKEY , M31  , BOTT1, M21  , RDIAM, M91  ],
	[BOTT2, BLOK2, OKEY , BLOK2, BKEY , BLOK2, BKEY , BLOK2, OKEY , BLOK2, BOTT2],
	[BLOK2, BDIAM, M21  , SPACE, M46  , SPACE, M46  , SPACE, M21  , BDIAM, BLOK2],
	[BOTT1, BLOK2, OKEY , BLOK2, SPACE, DOOR1, SPACE, BLOK2, OKEY , BLOK2, BOTT1],
	[M31  , BKEY , M46  , SPACE, SPACE, SPACE, SPACE, SPACE, M46  , BKEY , M31  ],
	[RKEY , BLOK2, SPACE, BLOK2, SPACE, BLOK2, SPACE, BLOK2, SPACE, BLOK2, RKEY ],
	[M31  , BKEY , M46  , SPACE, SPACE, SPACE, SPACE, SPACE, M46  , BKEY , M31  ],
	[BOTT1, BLOK2, OKEY , BLOK2, SPACE, SPACE, SPACE, BLOK2, OKEY , BLOK2, BOTT1],
	[BLOK2, BDIAM, M21  , SPACE, M46  , SPACE, M46  , SPACE, M21  , BDIAM, BLOK2],
	[BOTT2, BLOK2, OKEY , BLOK2, BKEY , BLOK2, BKEY , BLOK2, OKEY , BLOK2, DOOR2],
	[M91  , RDIAM, M21  , BOTT1, M31  , RKEY , M31  , BOTT1, M21  , RDIAM, M91  ]
] 
var floot21=[
	[BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2],
	[BLOK2, BLOK2, SPACE, SPACE, BLOK2, M67  , BLOK2, SPACE, SPACE, BLOK2, BLOK2],
	[BLOK2, SPACE, SPACE, BLOK2, BLOK2, M50  , BLOK2, BLOK2, SPACE, SPACE, BLOK2],
	[BLOK2, SPACE, SPACE, SPACE, BLOK2, M50  , BLOK2, SPACE, SPACE, SPACE, BLOK2],
	[BLOK2, BLOK2, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, BLOK2, BLOK2],
	[BLOK2, BLOK2, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, BLOK2, BLOK2],
	[BLOK2, BLOK2, BLOK2, SPACE, SPACE, BLOK2, SPACE, SPACE, BLOK2, BLOK2, BLOK2],
	[BLOK2, BLOK2, BLOK2, BLOK2, SPACE, DOOR1, SPACE, BLOK2, BLOK2, BLOK2, BLOK2],
	[BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2],
	[BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2],
	[BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2, BLOK2]
]